blank_issues_enabled: false
contact_links:
  - name: Best of AI Starters
    url: https://github.com/archestack/best-of-ai-starters
    about: Starters, boilerplates and templates for building AI apps are listed there.
